### ISSUE TITLE
ordered lists in tooltips updated to use upper case alphabet

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/homelessness-dashboard#122]
As a content strategist, i want tooltip information to use upper-case alphabet for ordered list.

**Comment by ablangworthy27** [comment]
@chiaberry this hasn't been fixed yet.

Newly Homeless - Individuals tooltip
should read: 
This count includes anyone who:
A. Hasn’t received homelessness services in the last 2 years, including those who have previously been homeless or are experiencing homelessness for the first time.
B. Is seeking service for the first time in Austin or Travis County, though they have received services elsewhere.

**Comment by chiaberry** [comment]
@ablangworthy27 should these tooltips have the same language? ![Screen Shot 2020-11-19 at 10.57.16 AM.png](https://images.zenhubusercontent.com/5d94ec32d5b3be000146f82d/befc1af2-37ad-4d14-a3be-46505b10f77d)

**Comment by ablangworthy27** [comment]
Yes, and the list needs to be applied in both places
