### ISSUE TITLE
Section enlargements

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#129]
As a user, I want the ability to enlarge the visualization blocks, so that I can see the details better.

As they are currently, the visualizations may not be accessible to all because they are limited in size. The text is also small.

**Comment by easherma** [comment]
FWIW if you use the zoom button on your browser, the text and graphics should scale proportionally. At 300% zoom they stack so that a single visualization is shown at a time.

**Comment by toribr** [comment]
In general, it's a bad idea to duplicate functionality found in the browser. @ablangworthy27 closing this, let me know if you have strong feelings.
