### ISSUE TITLE
Fix current tooltips

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#131]
As a user, I want the current tooltips to be replaced with a more accessible option so that I can access the information regardless of tech savviness or knowledge.

**Comment by toribr** [comment]
@chiaberry This icon is an .svg but coded as `<img>`. I'm not sure if I should provide you with a .svg that's the right contrast, or if we should go ahead and make the move to material icons. Thoughts?

**Comment by chiaberry** [comment]
I feel like it would be easier to just switch to material icons

**Comment by toribr** [comment]
You da boss. 
https://material.io/resources/icons/?search=info&icon=info&style=baseline #272727 
let's try  a bit bigger too: 20 x 20

**Comment by toribr** [comment]
Acceptance criteria:
• icon is changed to material icon
• icon has color of #272727
• icon is sized to 20x20
• icon has help text: "see amanda"

**Comment by ablangworthy27** [comment]
Correct me if I am wrong, but alt text for these icons or buttons shouldn't need to include "icon" or "button". It will read as a button or something clickable/hoverable automatically. 

help text/alt text: "More information"

**Comment by chiaberry** [comment]
https://deploy-preview-202--austin-homelessness-dashboard.netlify.app/

**Comment by chiaberry** [comment]
Is this good to merge?

**Comment by toribr** [comment]
I think so.
