### ISSUE TITLE
Connect Socrata API to Tableau

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#15]
Follow up with Eric on this process and his research

**Comment by dgarretthall** [comment]
Spoke with Nick about providing an estimate in Eric's absence. He said it's important that Eric provides the estimate since he doesn't have any context and isn't performing the work.

**Comment by easherma** [comment]
I’m not seeing this aspect as a priority if the data is only updated annually? Regardless my research shows its a functionality available in Tableau Desktop so this shouldn’t be a big deal. Folks at Austin Energy may be doing it already.
