### ISSUE TITLE
Missing Alternative text

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#172]
Missing alternative text

- Document language missing and Broken ARIA reference
- City Crest

Toprail:
- Metric icons
- Arrow (up/down) icons
- 'i' icon (option will be changed
 
Sections:
- 'i' icon (option will be changed

https://wave.webaim.org/report#/https://homelessness.dashboards.austintexas.gov/

**Comment by ablangworthy27** [comment]
@chiaberry not sure If I am actually needed for this?
