### ISSUE TITLE
Contrast Errors

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#173]
List of color contrast errors:
- Links in the header
- Glossary card
- Data card

https://wave.webaim.org/report#/https://homelessness.dashboards.austintexas.gov/

**Comment by ablangworthy27** [comment]
~~Would also add the light gray tooltips. Design team mentioned they rendered them very hard to notice.~~@toribr

Resolved in another issue.

**Comment by toribr** [comment]
Since the header will be reworked, we'll need to make sure that it's compliant. This issue is irrelevant now because design will be updated.
