### ISSUE TITLE
Heading Alerts

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#174]
Missing and redundant heading levels
- Metric title (Newly Homeless, People Sheltered, People Housed, Beds for Housing)
- Redundant heading

https://wave.webaim.org/report#/https://homelessness.dashboards.austintexas.gov/

**Comment by chiaberry** [comment]
@toribr same for this one, halp with exit criteria pls.

**Comment by toribr** [comment]
@chiaberry Apparently, instead of the heads being` <h5> `they need to be `<h3>` for better accessibility. I'm not sure what the right approach is as far as code, but essentially we need the `<h3>` to be set at the `<h5>` size. (I can't tell what trickle down implications that change might have)
