### ISSUE TITLE
ARIA

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#176]
- 26 ARIA
- 11 ARIA labels
- ARIA tabindex
- 2 ARIA hidden

https://wave.webaim.org/report#/https://homelessness.dashboards.austintexas.gov/

**Comment by benguhin** [comment]
These tags are showing that ARIA tags are working, which is great. Details here: https://www.w3.org/WAI/standards-guidelines/aria/
