### ISSUE TITLE
Heatmap + Google Analytics setup

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#177]
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:2002792,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by ablangworthy27** [comment]
@sarahscottr are analytics set up yet?

**Comment by chiaberry** [comment]
@ablangworthy27 I am assuming yes, this issue is referenced in this commit: https://github.com/cityofaustin/homelessness-dashboard/commit/1518075068c51f3d40aa28eb2c2626fe2a90e1c1

**Comment by chiaberry** [comment]
@sarahscottr , do you know where we can see analytics?

**Comment by toribr** [comment]
Closing this, and created new issue for starting over with GA.
