### ISSUE TITLE
Visualization Sizing

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#178]
Chart isn't fitted properly and there is a scrolling element in Section 3, Tab 2 (Housed, Individuals)

<img width="564" alt="Screen Shot 2020-09-16 at 12 12 29 PM" src="https://user-images.githubusercontent.com/21310597/93801876-50937380-fc08-11ea-867d-82f98cf3c08a.png">

**Comment by benguhin** [comment]
@sarahscottr can you let me know which browser you're experiencing this in? Haven't been able to replicate in the latest versions of Firefox and Chrome

**Comment by benguhin** [comment]
nvm, I see it now! was looking at the wrong table :/

**Comment by benguhin** [comment]
@sarahscottr if you can get the Tableau link for the Individuals in "Housing" to match the syntax/features of the link for Individuals in "Shelter," I think that will fix the problem.

--

Related links and screenshots:

### This is the tableau link it's pulling into the frame, which doesn't have an X-axis listed for years and doesn't autoscale to the frame provided:
https://public.tableau.com/views/Exits_15930134501040/Sheet1?:language=en&:display_count=y&:origin=viz_share_link&:embed=y&:showVizHome=n&:apiID=host6#navType=0&navSrc=Parse
<img width="613" alt="Screen Shot 2020-09-28 at 12 26 23 PM" src="https://user-images.githubusercontent.com/6953063/94465792-0ec57880-0186-11eb-8b01-a60540ac9884.png">


--
### The "Individuals" tab under "Shelter" is an example of how this should be performing, where it toggles from "Beds" to "Individuals" without bringing in the scrollbar:
<img width="561" alt="Screen Shot 2020-09-28 at 12 23 22 PM" src="https://user-images.githubusercontent.com/6953063/94465439-834be780-0185-11eb-8998-37652b239b5d.png">

It's pulling in this Tableau link, which has the X axis in view and auto-scales to the browser frame:
https://public.tableau.com/views/Changeinthetotalnumberofbedsusedtoshelterpeople/HousingandShelter2?:language=en&:display_count=y&:origin=viz_share_link&:embed=y&:showVizHome=n&:apiID=host2#navType=0&navSrc=Parse
<img width="612" alt="Screen Shot 2020-09-28 at 12 25 56 PM" src="https://user-images.githubusercontent.com/6953063/94465867-2997ed00-0186-11eb-9f33-0337b5d905c5.png">

This is what you'll want to see for the Individuals in "Housing" as well, in order for it to auto-scale to fit the iframe window.


@dgarretthall @jairPineros

**Comment by dgarretthall** [comment]
@benguhin Following up here on Sarah's behalf, is this a coding issue with the embedding text that you or @jairpineros can fix?

**Comment by benguhin** [comment]
@dgarretthall the first step would be getting the adjusted link from Tableau, which requires Tableau access. If @sarahscottr or others can create that link, me or @jairPineros can push the change

**Comment by ablangworthy27** [comment]
@sarahscottr is this stil outstanding on your end? I can't replicate, so I am assuming this can be closed but don't wanna jump the gun.
