### ISSUE TITLE
Quick design fixes for banner, as suggested by Chase and Tori

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#180]
- Banner blindness is a blocker for getting the disclaimer seen by users. The button is not standing out. Chase suggests a different color for the disclaimer button and making it a bit bigger. 
-General feedback is that the interface is too monochromatic (for example tooltips "i" disappears). Might want to try a more standout active state color, Alpha's blue hex# is 0050D8. 
-Work on the padding and make more generous like ATD Vision Zero dashboard,
-Could remove info about Echo from banner, since their participation is complicated? It takes up valuable space. We could add text in its place that is lifted from disclaimer. 

More dev lift:
Collapsible banner under toprail, kind of like Mass.gov

**Comment by sarahscottr** [comment]
Mocked up some changes based on the feedback - https://www.figma.com/proto/eot8AHPn65fcLNXvcjpyfd/Homelessness-Prototype?node-id=998%3A2&scaling=min-zoom

Need to get feedback

**Comment by ablangworthy27** [comment]
@sarahscottr I riffed off your design in Miro
https://miro.com/app/board/o9J_kiHTVRk=/

As discussed in pin-up, we really need to get a dev perspective on lift. The changes to color, etc... are easy but I don't know what is required to make this dropdown happen.

**Comment by ablangworthy27** [comment]
@chiaberry @toribr @sarahscottr Should we all sync on this?

**Comment by toribr** [comment]
Yes, we should. I have some questions about the design, and we can discuss dev effort.

**Comment by chiaberry** [comment]
https://share.goabstract.com/27ac589a-036d-47be-89f3-8fda37247e5b?collectionLayerId=3774d17e-45b5-4637-b07f-c08b0607c6d0&mode=design

**Comment by chiaberry** [comment]
https://180-banner--austin-homelessness-dashboard.netlify.app/
