### ISSUE TITLE
Data stories workshops

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#197]
As a content strategist, I could better write content for the City Services Dashboard if I had a better idea of what each department/group is providing for people experiencing homelessness.

We need to:

- [ ] Finalize workshop structure and do a run-through

- [ ] Setup workshop meeting times. @sarahscottr can you list the groups here? 

- [ ] Host the workshops

- [ ] Consolidate the findings and make issues

**Comment by sarahscottr** [comment]
@ablangworthy27 the list is here - https://airtable.com/tblfoEnFIWkCdAB2L/viwL9ul30q9FWOH5U?blocks=hide

Waiting on Lara to fill out some of the information and send the initial introductions.
