### ISSUE TITLE
create tooltips for housing/shelter data visualization

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/homelessness-dashboard#2]
Housing and Shelter tooltip

- [x] Draft content
- [x] Get a review from Sarah
- [ ] Implement into dashboard

**Comment by ablangworthy27** [comment]
@sarahscottr my draft is in a [google doc.](https://docs.google.com/document/d/1KnSmZlwv9uwnRMonf1I8UHt8e7acqALO1BzmRDADK_Q/edit#heading=h.or8ncc7n8eiz)

**Comment by sarahscottr** [comment]
@ablangworthy27 made comments let me know if you have any questions
