### ISSUE TITLE
Tableau License

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#26]
Lara has reached out the AE and is in the process of talking to their Tableau contact.

**Comment by sarahscottr** [comment]
Lara is in talks with Tableau to obtain license. Going to use Tableau public, to ensure there isn't a wait time of gap.

**Comment by easherma** [comment]
I don't see a need for me to have a license, so besides @sarahscottr's there should be one more up for grabs.
