### ISSUE TITLE
Dashboard has links to original data source for each visualization

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#29]
Potential users that are more accustomed to working with data may want to do a deep dive, so we'd like to share the raw datasets. 

Ideally these links would link directly back to the data used in visualization, though that will be a maintenance concern in case those links change.

**Comment by easherma** [comment]
MVP version of this is a 3, something for long term maintenance might be more of a 5 (how do we know if data source link has changed? Would the visualization break, etc?

**Comment by easherma** [comment]
Maybe talk to Chase about where that data source link would be best on the design.

**Comment by sarahscottr** [comment]
Link to the Housing and Shelter data - https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/

**Comment by easherma** [comment]
This is provided via the Tableau embed panel, but if we end up hiding it we may need to link to it in other ways. 

For a dev, this would be easy to do. We are already tracking the list of links in vizList.js. We'd just need to code out a new section to have a link to data source for each. We could even have the title of the data viz function as a link to the data if we wanted. 

But the simplest thing might be to just leave the data link that Tableau has as part of the embed code. I'd recommend talking to their support for more options about good ways to handle that.
