### ISSUE TITLE
create disclaimer

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/homelessness-dashboard#3]
### As a city employee I want it to be clear that there is complexity to the data so that community members understand that there might be incorrect data/etc.

**Acceptance Criteria**
Community member when visiting the dashboard understands  that data may be out of date

**Comment by ablangworthy27** [comment]
https://docs.google.com/document/d/17VHperrEuCYzznNYwCTYdBJDga47-Jarpbymp0KtbLk/edit
