### ISSUE TITLE
Sync on documentation/visualization components with sara

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#56]
We're still gonna meet, but Sarah is also updating the doc with what we're using for MVP:
https://docs.google.com/document/d/18I4ZxKQHip_S1PDW0vVSe9Darbblqj4fpzIQN8aAkLE/edit#

**Comment by ablangworthy27** [comment]
@easherma @sarahscottr do we still need to do this?

**Comment by sarahscottr** [comment]
@ablangworthy27 @easherma that would be good but i don't know what everyone's availability is

**Comment by ablangworthy27** [comment]
I'm free all day today

**Comment by sarahscottr** [comment]
@easherma @ablangworthy27 same question. i'm free tomorrow and this afternoon.
