### ISSUE TITLE
Develop site header

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#58]
As seen on: 
https://www.figma.com/file/eot8AHPn65fcLNXvcjpyfd/Homelessness-Prototype?node-id=0%3A1

We've two logos, placeholder copy, and a data button. 

We have two logos, can we confirm that these are the logos we want on the header, do we need any other logos? 

Do the logos link anywhere?

There is placeholder copy on figma for the center of the header. What should the placeholder content say? 

What does the data button do? Does it need to be there for MVP?

**Comment by easherma** [comment]
We've two logos, placeholder copy, and a data button. 

Logos? Easy, we got logos. Lets make sure those are the logos we want. 

What should the placeholder content say? 

What does the data button do?

**Comment by ablangworthy27** [comment]
@easherma re: the button. I don't think it needs to be there for MVP, and in fact I think a text hyperlink might be the way to go. You can see my content (linked in the related issue) for more context.
