### ISSUE TITLE
Develop/resolve footer links 

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#59]
For here: 
https://www.figma.com/file/eot8AHPn65fcLNXvcjpyfd/Homelessness-Prototype?node-id=0%3A1

Figure out if we need to add to layout, where those links go, etc. 

Tech wise, linking out to external links for these 'buttons' is simple. But there is a larger question about what we want those links to be or what should happen when a user interacts. That is currently the bulk of this issue. 

If we want, once we have clarity on that we can convert to an epic and break it up into smaller tasks. 

Current design has the footer with 3 large buttons with text. We need to know the following for each: 

* City Services
What/who is this for? What is the expected behavior? (can we write a user story? )
Internal or external link? Do we have a URL we can link to?
* Glossary
What/who is this for? What is the expected behavior? (can we write a user story? )
Internal or external link? Do we have a URL we can link to?
    * there was an existing glossary @ablangworthy27 and Sarah started putting together. It may need to just be updated, and may just need a home. 
* Resources
What/who is this for? What is the expected behavior? (can we write a user story? )
Internal or external link? Do we have a URL we can link to?

Suggestion: if we don't have existing external links for these and we want design of the dashboard to eventually conform to the design of alpha.austin.gov, can we just make some info and/or service pages on alpha and link to those here?

**Comment by easherma** [comment]
If we dont have answers for some of those (like City Resources), we'll have to figure out what to do in the meantime for MVP. Its going to take plenty of stakeholder engagement to figure out where these links go and what is on these links. 

Additionally clarity about what pieces of those links fall under the scope of this particular project is going to help us decide what to do for MVP.

**Comment by easherma** [comment]
from Lara: 
> Howdy all, there still is a link to the Glossary on the Ausitntexas.gov/homelessness page:http://austintexas.gov/department/austins-homeless-strategy-covid-19-support and here is the direct link to the glossary: https://www.austintexas.gov/department/homelessness-glossary

**Comment by ablangworthy27** [comment]
I'm realizing that since this iteration of the dashboard is going to be embedded on austintexas.gov, we should probably remove the footer for now. These links are already going to exist in the nav.

**Comment by ablangworthy27** [comment]
@easherma 

Link 1 - Austin's Homelessness Strategy 
http://austintexas.gov/homelessness/

Link 2 - Glossary
http://austintexas.gov/department/homelessness-glossary

Link 3 - Data
https://data.austintexas.gov/browse?q=homeless&sortBy=relevance
