### ISSUE TITLE
Develop 'Count' components for the top rail

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#60]
See prototype: 
https://www.figma.com/file/eot8AHPn65fcLNXvcjpyfd/Homelessness-Prototype?node-id=0%3A1

Counts at the top probably will be hard-coded html for now

**Comment by easherma** [comment]
Data for the counts is accurate as in figma, will be updated annually. 
@ablangworthy27 can you link to the tooltip content for these here?

**Comment by ablangworthy27** [comment]
Here is my copy for the top-rail tool tips. I am also incorporating some revisions today.
https://docs.google.com/document/d/1UGbICm5B60uZqWizogJHENMPt8TNHUlV19-4oMVsTxs/edit#
