### ISSUE TITLE
Develop custom tooltip components

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#63]
@ablangworthy27 has written _draft_ content for tooltips

We need to code them into the layout, ideally in a way where the content can easily be updated later.

**Comment by easherma** [comment]
Doing a good job making these easy to edit will make it easier for non-devs to update the top rail counts in the future too!

**Comment by ablangworthy27** [comment]
Here is my copy. I am incorporating revisions today.
https://docs.google.com/document/d/1KnSmZlwv9uwnRMonf1I8UHt8e7acqALO1BzmRDADK_Q/edit#

**Comment by easherma** [comment]
These are implemented for top rail components.

For the data layers its a bit more complicated, as we want to have different tooltips depending on the active viz.
