### ISSUE TITLE
Draft header content to go with "Data" button

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#66]
There is a button for data.austin.gov, and some lorem ipsum content that needs to be written

**Comment by easherma** [comment]
Related to https://github.com/cityofaustin/homelessness-dashboard/issues/58

**Comment by ablangworthy27** [comment]
I combined the disclaimer and banner (header) content into [one document.](https://docs.google.com/document/d/17VHperrEuCYzznNYwCTYdBJDga47-Jarpbymp0KtbLk/edit#)

I think option 1 is the way to go. This means there is a banner/header (as mocked up in Figma) and there is a pop-up for the disclaimer.
