### ISSUE TITLE
Sort out differences between prototype and embedded Tableau visualizations 

### ISSUE THREAD

**Issue by easherma** [cityofaustin/homelessness-dashboard#76]

**Comment by wilhitem** [comment]
not sure if this is helpful, but found this page on customizing the iframes. they list out parameters in the examples like tabs/toolbar/filters/name as things to exclude from the views. i'm sure there is more to getting them to parity, but wanted to have it in here :)
https://help.tableau.com/current/pro/desktop/en-us/embed_dashboard.htm
