### ISSUE TITLE
Get feedback from Alpha design team

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#78]
A meeting has been scheduled for 7/16 with Chase and Tori. The issue I made for them was pretty general in the feedback we are looking for. If there are any specific questions we want to address, lets document them here.

**Comment by sarahscottr** [comment]
Dashboard Visualization Design Guide/Documentation  - https://docs.google.com/document/d/1edExMyz9rX97TZRvm40C5WIcTG17EnGt_JlKt20L0Jo/edit?usp=sharing
