### ISSUE TITLE
Create tooltip content for Individuals Sheltered data visualization

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#8]
Funding tooltip

- [x]  Draft content
- [x]  Get a review from Sarah
- [ ]  Implement into dashboard

**Comment by ablangworthy27** [comment]
@sarahscottr my draft is in [this google doc](https://docs.google.com/document/d/1KnSmZlwv9uwnRMonf1I8UHt8e7acqALO1BzmRDADK_Q/edit#heading=h.or8ncc7n8eiz). I haven't yet included info about specific demographics. I think we know which ones we want to focus on, but we are not currently showing them in the MVP mockup.

**Comment by sarahscottr** [comment]
@ablangworthy27 made comments let me know if you have other questions
