### ISSUE TITLE
Create tooltip content for Returns to Homelessness data visualization

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/homelessness-dashboard#9]
Funding tooltip

- [x]  Draft content
- [x]  Get a review from Sarah
- [ ]  Implement into dashboard

**Comment by ablangworthy27** [comment]
Hi @sarahscottr doc is [here](https://docs.google.com/document/d/1KnSmZlwv9uwnRMonf1I8UHt8e7acqALO1BzmRDADK_Q/edit#heading=h.or8ncc7n8eiz)

**Comment by sarahscottr** [comment]
@ablangworthy27 made comments let me know if you have any questions
