### ISSUE TITLE
Top-rail formatting bug

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#97]
## Describe the bug
The second measure in the top rail is a short length than the rest of the measures.

## URL
https://homelessness-dashboard.netlify.app/

## To Reproduce
1. Open up the website in Chrome browser

## Current behavior
The second measure in the top rail doesn't size to the same length as the other measures

## Expected behavior
All measures in the top rail have the same length

## Screenshots
<img width="1129" alt="Screen Shot 2020-08-03 at 9 53 28 AM" src="https://user-images.githubusercontent.com/21310597/89205791-e3efe700-d57d-11ea-99aa-dbab793be56d.png">

## Device and browser
Chrome, Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by easherma** [comment]
I can't replicate this issue, though I would expect that the formatting bug is due to the fluid layout and the fact that the icons aren't loading properly in this case.
