### ISSUE TITLE
Visualization updating bug

### ISSUE THREAD

**Issue by sarahscottr** [cityofaustin/homelessness-dashboard#99]
## Describe the bug
The second section and third layer (Shelter, Demographics) visualization isn't updating when change are made in Tableau 

## URL
https://homelessness-dashboard.netlify.app/

## To Reproduce
1. Open up Dashboard in Chrome browser

## Expected behavior
Changes made in Tableau visualization from Tableau Public to update on the Dashboard when they're pushed to the Tableau server.

## Screenshots
<img width="558" alt="Screen Shot 2020-08-03 at 9 53 37 AM" src="https://user-images.githubusercontent.com/21310597/89206444-eef74700-d57e-11ea-8b54-64bf198bfd70.png">

## Device and browser
macOS, Mojave, 10.14.6 (18G6020)
Chrome, Version 84.0.4147.105 (Official Build) (64-bit)

## Additional context
Shows out of date format, and potentially data.

**Comment by sarahscottr** [comment]
Also appears to happen in Safari, Version 13.1.2 (14609.3.5.1.5), and it appear to also shrink the fourth measure if the browser width is condensed

<img width="954" alt="Screen Shot 2020-08-03 at 6 16 07 PM" src="https://user-images.githubusercontent.com/21310597/89236249-a4dd8800-d5b5-11ea-94cb-1e15c08eb571.png">

**Comment by easherma** [comment]
I wasn't able to replicate this issue, but I wouldn't be surprised if there is flaky behavior with the iFrames. This would be a good thing to talk to Tableau support about, and to also see if things get less flaky once we're embedding visualizations from a paid account.
